### PR TITLE
[WIP] Create flexible entity

### PR DESCRIPTION
**Pull request by stood**
ToDo list:
- [x] Create Flexible Type
- [x] Create Flexible Entity Choice list
- [x] Query (Options Where and Suffix)
- [x] Multiple
- [x] Preferred Choices
- [x] GroupBy
- [x] Docs
- [x] Test & Review

### CODE REVIEW

**Comment by chanmix51** [comment]
If I may dare a comment about the coding conventions, Pomm uses underscore format for attributes and variables. AFAIK, the bundle follows the same conventions. I let @sanpii chose what to do with that.

**Comment by stood** [comment]
Oh yes I'm sorry :) I will correct this in the Test & Review task :)

**Comment by sanpii** [comment]
Can you add some fuctionnal tests to pomm bundle? This will probably accelerate my review :yum:

**Comment by sanpii** [comment]
I tried to testing this PR, but I have some difficults with the form component.

I think, it miss some glue for the bundle (at least a [form type extension](https://symfony.com/doc/current/form/create_form_type_extension.html)) and I had an error with `FlexibleEntityType` constructor parameters 😢

**Pull request closed without merging**
